name: FastAPI CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "main" ]

jobs:
  fastapi_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest  # Ensure you have tests in place, using pytest

  deploy_fastapi:
    runs-on: ubuntu-latest
    needs: fastapi_ci  # Ensures the CI tests pass before deployment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy FastAPI
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            REPO_DIR="app"

            # Clone or update the repo if it exists
            if [ ! -d "$REPO_DIR" ]; then
              git clone https://github.com/theMirmakhmudov/FastAPI-Users-Task-v2.git $REPO_DIR
            else
              cd $REPO_DIR
              git pull origin master  # Pull the latest changes
            fi
            cd $REPO_DIR

            # Set up a virtual environment if not already created
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            # Check if a FastAPI app is already running with Uvicorn and kill it if needed
            if pgrep -f "uvicorn"; then
              pkill -f "uvicorn"
            fi

            # Start the FastAPI app using Uvicorn in the background
            nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload &
