name: FastAPI CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy_fastapi:
    runs-on: ubuntu-latest
    needs: fastapi_ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy FastAPI
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e 

            REPO_DIR="app"

            if [ ! -d "$REPO_DIR" ]; then
              # Ensure the repo is cloned properly
              git clone https://github.com/theMirmakhmudov/FastAPI-Users-Task-v2.git $REPO_DIR
            else
              # Ensure we're inside the repository directory
              cd $REPO_DIR
              git fetch --all
              git reset --hard origin/master
            fi

            cd $REPO_DIR

            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            # Restart FastAPI app using Uvicorn
            if pgrep -f "uvicorn"; then
              pkill -f "uvicorn"
            fi
            nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload &
