name: FastAPI CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "main" ]

jobs:
  fastapi_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest

  deploy_fastapi:
    runs-on: ubuntu-latest
    needs: fastapi_ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy FastAPI
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e 

            REPO_DIR="fastapi-app"

            # Clone or update the repository
            if [ ! -d "$REPO_DIR" ]; then
              echo "Cloning repository into $REPO_DIR..."
              git clone https://github.com/theMirmakhmudov/FastAPI-Users-Task-v2.git $REPO_DIR
            else
              echo "Repository already exists, pulling the latest changes..."
              cd $REPO_DIR
              git pull origin master
              cd ..
            fi

            # Check if the repo directory exists after clone/pull
            if [ ! -d "$REPO_DIR" ]; then
              echo "Error: The directory '$REPO_DIR' does not exist after cloning or pulling the repository."
              exit 1
            fi

            # Navigate into the repository directory
            echo "Navigating into $REPO_DIR directory..."
            cd $REPO_DIR

            # Create virtual environment if it doesn't exist
            if [ ! -d "venv" ]; then
              echo "Creating virtual environment..."
              python3 -m venv venv
            fi

            # Activate the virtual environment
            source venv/bin/activate

            # Install dependencies
            echo "Installing dependencies..."
            pip install --upgrade pip
            pip install -r requirements.txt

            # Start FastAPI using systemd
            echo "Starting FastAPI service..."
            sudo systemctl stop fastapi.service
            sudo systemctl disable fastapi.service
            sudo systemctl start fastapi.service
            sudo systemctl enable fastapi.service

            echo "Deployment completed successfully!
